"""Maze grid generation and item placement."""

from mazegenerator import MazeGenerator
from src.config import load_config
from src.grid.cell import Cell, StateType, create_cell
import random


class Grid:
    """Maze grid made of cells, generated by ``MazeGenerator``."""

    def __init__(self, width: int, height: int, seed: int | None) -> None:
        """Initialize the grid and generate the maze.

        Args:
            width: Number of columns of the maze.
            height: Number of rows of the maze.
            seed: Seed for the maze generation. If ``None``,
                ``generate`` is not called explicitly.

        Raises:
            Exception: If the maze generation fails or returns no data.
        """
        self.width: int = width
        self.height: int = height
        self.seed: int | None = seed
        self.grid: list[list[Cell]] = []
        self.maze_load()

    def maze_load(self) -> None:
        """Generate the maze and build ``self.grid`` from it.

        Raises:
            Exception: If ``MazeGenerator`` raises an error, or if the
                generated maze is empty.
        """
        try:
            m = MazeGenerator(size=(self.width, self.height), perfect=False)
            if isinstance(self.seed, int):
                m.generate(seed=self.seed)
        except Exception as e:
            raise Exception(f"Error: maze generation is failed, {e}")
        if not m.maze:
            raise Exception("Error: maze data is empty")
        grid: list[list[Cell]] = []
        for y, row in enumerate(m.maze):
            row_cells: list[Cell] = []
            for x, value in enumerate(row):
                cell = create_cell(x, y, value)
                row_cells.append(cell)
            grid.append(row_cells)
        self.grid = grid

    def get_cell(self, y: int, x: int) -> Cell:
        """Return the cell at the given position.

        Coordinates outside the grid are clamped to the nearest border.

        Args:
            y: Row index.
            x: Column index.

        Returns:
            The cell at ``(y, x)`` after clamping.
        """
        y = max(0, min(y, self.height - 1))
        x = max(0, min(x, self.width - 1))
        return self.grid[y][x]

    def place_items(self, pacgum_count: int) -> None:
        """Place super pacgums and pacgums in the maze.

        A super pacgum is placed in each of the four corners. Pacgums
        are then placed on randomly chosen cells that are empty, not
        the center cell, and have at least one open side.

        Args:
            pacgum_count: Number of pacgums to place. If there are not
                enough available cells, it is clamped and a warning is
                printed.
        """
        count = pacgum_count
        corners = [
            (0, 0),
            (self.width - 1, 0),
            (0, self.height - 1),
            (self.width - 1, self.height - 1)
        ]
        for x, y in corners:
            self.get_cell(y, x).state_type = StateType.SUPER_PACGUM
        maze_center = self.get_center_position()
        available = []
        for row in self.grid:
            for cell in row:
                if (cell.state_type == StateType.EMPTY
                        and cell is not maze_center
                        and any([cell.north, cell.east, cell.south, cell.west])):
                    available.append(cell)
        if count > len(available):
            print(
                f"Warning: requested {count} pacgum but only "
                f"{len(available)} cells available, clamping"
            )
            count = len(available)
        selected = random.sample(available, count)
        for cell in selected:
            cell.state_type = StateType.PACGUM

    def is_all_empty(self) -> bool:
        """Check whether every cell of the grid is empty.

        Returns:
            True if no cell contains a pacgum or super pacgum,
            False otherwise.
        """
        for row in self.grid:
            for cell in row:
                if cell.state_type != StateType.EMPTY:
                    return False
        return True

    def get_center_position(self) -> Cell:
        """Return the center cell of the maze.

        Finds the first fully walled cell and returns the cell two
        rows below and three columns to its right. If no fully walled
        cell exists, falls back to the geometric center of the grid.

        Returns:
            The center cell of the maze.
        """
        for row in self.grid:
            for cell in row:
                if not any([cell.north, cell.east, cell.south, cell.west]):
                    return self.get_cell(cell.y + 2, cell.x + 3)
        return self.get_cell(self.height // 2, self.width // 2)


if __name__ == "__main__":
    config = load_config("data/configuration.json")
    # Niveau 1
    grid1 = Grid(
        width=config.levels[0].width,
        height=config.levels[0].height,
        seed=config.seed
    )
    grid1.place_items(config.pacgum)
